CLASS zcl_issue_5262_abapgit DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    CLASS-METHODS main.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS zcl_issue_5262_abapgit IMPLEMENTATION.
  METHOD main.
    CALL TRANSFORMATION zissue_5262_abapgit SOURCE root = sy-subrc RESULT XML DATA(result).
  ENDMETHOD.
ENDCLASS.
